# Generated by Django 4.2.15 on 2024-08-18 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("containerlab", "0002_alter_topology_dynamic_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopologyTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("template_content", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Topology Template",
                "verbose_name_plural": "Topology Templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="topology",
            name="custom_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="containerlab_topology",
                to="containerlab.topologytemplate",
            ),
        ),
    ]
